plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base { archivesName = project.archives_base_name }

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    def versionValue = project.version
    def minecraftVersion = project.minecraft_version
    inputs.property 'version', versionValue
    inputs.property 'minecraft_version', minecraftVersion
    from('assets') { into 'assets' }
    from('spotifyhud') { into 'spotifyhud' }
    filesMatching('fabric.mod.json') {
        expand version: versionValue, minecraft_version: minecraftVersion
    }
}

tasks.withType(JavaCompile).configureEach { options.release = 25 }

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    def archiveName = project.archives_base_name
    from('LICENSE') { rename { "${it}_${archiveName}" } }
}
